<?php


namespace App\Form;


use App\Entity\Client;
use Doctrine\DBAL\Types\TextType;
use function Sodium\add;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ClientType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        //parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
        $builder
            ->add('nomClient', TextType::class,[
                'label' => 'Nom',
            ])
            ->add('prenomClient', TextType::class,[
                'label' => 'Prenom'
            ])
            ->add('portable', TextType::class,[
                'label' => 'Portable',
            ])
            ->add('paiements', TextType::class,[
                'label' => 'Paiements',
            ]);
    }


    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Client::class,
        ]);
    }
}